import SwiftUI
import EventKit
struct CalendarView:View{@Environment(AppState.self)private var app;@State private var date=Date();@State private var selected:ActivityEvent?
 var eventsForDay:[ActivityEvent]{app.events.events.filter{Calendar.current.isDate($0.selectedStart,inSameDayAs:date)}}
 var body:some View{NavigationStack{List{Section{DatePicker("Date",selection:$date,displayedComponents:.date).datePickerStyle(.graphical)};Section("Events"){if eventsForDay.isEmpty{Text("No plans for this date").foregroundStyle(.secondary)};ForEach(eventsForDay){e in Button{selected=e}label:{EventRow(event:e,profile:app.profiles.profiles.first{$0.id==e.profileID})}}}Section("Upcoming"){ForEach(app.events.upcoming.prefix(5)){e in Button{date=e.selectedStart;selected=e}label:{EventRow(event:e,profile:app.profiles.profiles.first{$0.id==e.profileID})}}};Section("Connected calendars"){CalendarConnectionRow(name:"Apple Calendar",status:"Allow access",action:connectApple);CalendarConnectionRow(name:"Google Calendar",status:"Setup required",action:nil);CalendarConnectionRow(name:"Microsoft Outlook",status:"Setup required",action:nil)}}.navigationTitle("Calendar").sheet(item:$selected){EventDetailView(event:$0)}.onChange(of:app.selectedEventID){_,id in if let id,let e=app.events.events.first(where:{$0.id==id}){date=e.selectedStart;selected=e;app.selectedEventID=nil}}.onAppear{if let id=app.selectedEventID,let e=app.events.events.first(where:{$0.id==id}){date=e.selectedStart;selected=e;app.selectedEventID=nil}}}}
 func connectApple(){Task{_ = try? await EKEventStore().requestFullAccessToEvents()}}
}
struct CalendarConnectionRow:View{let name,status:String;let action:(()->Void)?;var body:some View{HStack{Text(name);Spacer();if let action{Button(status,action:action)}else{Text(status).font(.caption).foregroundStyle(.secondary)}}}}
struct EventDetailView:View{let event:ActivityEvent;@Environment(AppState.self)private var app;@Environment(\.dismiss)private var dismiss;@State private var model=AnalysisViewModel();@State private var showResults=false
 var profile:UserProfile?{app.profiles.profiles.first{$0.id==event.profileID}}
 var body:some View{NavigationStack{List{Section{Text(event.plan.activityName).font(.title2.bold());LabeledContent("Profile",value:profile?.name ?? "Unknown");LabeledContent("Date",value:event.selectedStart.formatted(date:.long,time:.omitted));LabeledContent("Time",value:"\(event.selectedStart.formatted(date:.omitted,time:.shortened))–\(event.endTime.formatted(date:.omitted,time:.shortened))");LabeledContent("Duration",value:"\(event.plan.durationMinutes) min");Text(event.plan.location.formattedAddress)};Section("Environmental conditions"){if let a=event.analysis{LabeledContent("Fine particle pollution",value:a.pm25Mean.map{airText($0)} ?? "Unavailable");LabeledContent("Feels like",value:a.apparentTemperatureC.map{"\(Int($0.rounded()))°C"} ?? "Unavailable");Text("Last analyzed \(a.analyzedAt.formatted())").font(.caption).foregroundStyle(.secondary)}else{Text("Not analyzed")}};Section("Exposure"){if let r=event.analysis?.reductionPercent{Text("This selected plan had \(Int(r.rounded()))% lower modeled particle exposure than the original plan.")}else{Text("This is the original plan.")}};if let p=profile,p.medicalConditions.contains(where:{$0.localizedCaseInsensitiveContains("asthma")}){Section("Health information"){Text("Because this profile includes asthma, we've included air-quality guidance relevant to people with respiratory conditions.");Link("View EPA guidance",destination:URL(string:"https://www.airnow.gov/aqi/aqi-basics/")!)}};Section("What you can change"){Button("Check alternatives again"){showResults=true}};Section("Data"){LabeledContent("Source",value:event.analysis?.source ?? "Not available")}}.navigationTitle("Plan details").toolbar{Button("Done"){dismiss()}}.sheet(isPresented:$showResults){NavigationStack{ResultsView(plan:event.plan)}}}}
 func airText(_ v:Double)->String{v<=9 ? "Good · \(Int(v.rounded())) µg/m³":(v<=35 ? "Moderate · \(Int(v.rounded())) µg/m³":"Elevated · \(Int(v.rounded())) µg/m³")}
}
