import SwiftUI
struct HomeView:View{@Environment(AppState.self)private var app;@State private var location=LocationManager();@State private var showingProfiles=false;@State private var showingAI=false
 var body:some View{NavigationStack{ScrollView{VStack(alignment:.leading,spacing:24){HStack{VStack(alignment:.leading){Text(greeting).font(.title.bold());if let p=app.profiles.selectedProfile{Button("Planning for: \(p.name)  ▾"){showingProfiles=true}.font(.subheadline)}};Spacer()};conditions;hourly;Button{showingAI=true}label:{Label("Plan with AI",systemImage:"sparkles").frame(maxWidth:.infinity)}.buttonStyle(.borderedProminent).controlSize(.large);upcoming}.padding()}.navigationTitle("Home").navigationBarTitleDisplayMode(.inline).sheet(isPresented:$showingProfiles){ProfileSwitcher()}.sheet(isPresented:$showingAI){AIPlannerView()}.task{await refresh()}.task{while !Task.isCancelled{try? await Task.sleep(for:.seconds(60));await refresh()}}}}
 var greeting:String{let h=Calendar.current.component(.hour,from:Date());return h<12 ? "Good morning":(h<17 ? "Good afternoon":"Good evening")}
 @ViewBuilder var conditions:some View{VStack(alignment:.leading,spacing:12){HStack{Text("Current conditions").font(.title2.bold());Spacer();Button{Task{await refresh(force:true)}}label:{Image(systemName:"arrow.clockwise")}.disabled(app.environment.isLoading)};Text(app.environment.currentLocationName).font(.subheadline).foregroundStyle(.secondary);if let c=app.environment.current,let s=c.series.samples.min(by:{abs($0.timestamp.timeIntervalSinceNow)<abs($1.timestamp.timeIntervalSinceNow)}){LazyVGrid(columns:[GridItem(.flexible()),GridItem(.flexible())],spacing:10){ConditionCard(title:"Temperature",value:s.temperatureC.map{"\(Int($0.rounded()))°C"} ?? "—",detail:"Current forecast",icon:"thermometer.medium");ConditionCard(title:"Air quality",value:airLabel(s.pm25),detail:s.pm25.map{"Fine particles · \(Int($0.rounded())) µg/m³"} ?? "Unavailable",icon:"aqi.medium");ConditionCard(title:"UV",value:uvLabel(s.uvIndex),detail:s.uvIndex.map{"Index · \(String(format:"%.1f",$0))"} ?? "Unavailable",icon:"sun.max");ConditionCard(title:"Feels like",value:s.apparentTemperatureC.map{"\(Int($0.rounded()))°C"} ?? "—",detail:"Heat",icon:"sun.max.trianglebadge.exclamationmark")};Text("App checked \(c.checkedAt.formatted(date:.omitted,time:.shortened)) · Forecast retrieved \(c.series.fetchedAt.formatted(date:.omitted,time:.shortened))").font(.caption).foregroundStyle(.secondary)}else{ContentUnavailableView("Add a location",systemImage:"location",description:Text("Allow location or create a profile with a home ZIP to see conditions."))};if let e=app.environment.errorMessage{Text(e).font(.caption).foregroundStyle(.secondary)}}}
 @ViewBuilder var hourly:some View{VStack(alignment:.leading){Text("Hourly").font(.title2.bold());if let samples=app.environment.current?.series.samples.filter({$0.timestamp >= Date().addingTimeInterval(-3600)}).prefix(12){ScrollView(.horizontal,showsIndicators:false){HStack{ForEach(Array(samples),id:\.timestamp){s in VStack(spacing:8){Text(s.timestamp.formatted(date:.omitted,time:.shortened)).font(.caption);Image(systemName:s.pm25.map{$0<12 ? "leaf":"aqi.medium"} ?? "cloud");Text(s.temperatureC.map{"\(Int($0.rounded()))°"} ?? "—").font(.headline);Text(s.precipitationProbability.map{"\(airLabel(s.pm25)) · \(Int($0.rounded()))% rain"} ?? airLabel(s.pm25)).font(.caption2).foregroundStyle(.secondary)}.frame(width:82,height:105).background(.thinMaterial,in:RoundedRectangle(cornerRadius:8))}}}}}}
 @ViewBuilder var upcoming:some View{VStack(alignment:.leading,spacing:10){Text("Upcoming plans").font(.title2.bold());if app.events.upcoming.isEmpty{Text("No upcoming plans yet.").foregroundStyle(.secondary)}else{ForEach(app.events.upcoming.prefix(5)){event in Button{app.openEvent(event)}label:{EventRow(event:event,profile:app.profiles.profiles.first{$0.id==event.profileID})}.buttonStyle(.plain)}}}}
 func refresh(force:Bool=false)async{if let l=location.location{let a=ActivityLocation(name:location.placeName,formattedAddress:location.placeName,latitude:l.coordinate.latitude,longitude:l.coordinate.longitude,timeZoneIdentifier:nil);app.environment.currentLocationName=location.placeName;await app.environment.refresh(location:a,force:force)}else if let zip=app.profiles.selectedProfile?.homeZipCode,let a=try? await AddressSearchService().resolveAddress(zip){app.environment.currentLocationName=a.name;await app.environment.refresh(location:a,force:force)}}
 func airLabel(_ v:Double?)->String{guard let v else{return "Unavailable"};return v<=9 ? "Good":(v<=35 ? "Moderate":"Elevated")}
 func uvLabel(_ v:Double?)->String{guard let v else{return "Unavailable"};return v<3 ? "Low":(v<6 ? "Moderate":(v<8 ? "High":"Very high"))}
}
extension EnvironmentStore{var currentLocationName:String{get{UserDefaults.standard.string(forKey:"currentLocationName") ?? "Your area"}set{UserDefaults.standard.set(newValue,forKey:"currentLocationName")}}}
struct ConditionCard:View{let title,value,detail,icon:String;var body:some View{VStack(alignment:.leading,spacing:6){Image(systemName:icon).foregroundStyle(.tint);Text(value).font(.title2.bold());Text(title).font(.headline);Text(detail).font(.caption).foregroundStyle(.secondary)}.frame(maxWidth:.infinity,minHeight:125,alignment:.leading).padding(14).background(Color.secondary.opacity(0.09),in:RoundedRectangle(cornerRadius:8))}}
struct EventRow:View{let event:ActivityEvent;let profile:UserProfile?;var body:some View{HStack{VStack(alignment:.leading,spacing:4){Text(event.plan.activityName.uppercased()).font(.caption.bold());Text(profile?.name ?? "Profile").font(.headline);Text(event.selectedStart.formatted(date:.abbreviated,time:.shortened));Text(event.plan.location.name).font(.caption).foregroundStyle(.secondary).lineLimit(1)};Spacer();Image(systemName:"chevron.right").foregroundStyle(.tertiary)}.padding(.vertical,8)}}
struct ProfileSwitcher:View{@Environment(AppState.self)private var app;@Environment(\.dismiss)private var dismiss;var body:some View{NavigationStack{List{ForEach(app.profiles.profiles){p in Button{app.profiles.select(p.id);dismiss()}label:{ProfileCard(profile:p,selected:p.id==app.profiles.selectedProfileID)}}}.navigationTitle("Planning for")}}}
