import SwiftUI

struct OnboardingView:View {
 @Environment(AppState.self) private var app
 @State private var step=0;@State private var terms=false;@State private var privacy=false;@State private var location=LocationManager();@State private var manualLocation="";@State private var creatingProfile=false
 var body:some View{NavigationStack{VStack(alignment:.leading,spacing:24){Spacer();Image(systemName:icon).font(.system(size:44)).foregroundStyle(.tint);Text(title).font(.largeTitle.bold());Text(bodyText).font(.title3).foregroundStyle(.secondary);content;Spacer();Button(step==4 ? "Start planning":(step==3 ? "Continue to profiles":"Continue")){advance()}.buttonStyle(.borderedProminent).controlSize(.large).frame(maxWidth:.infinity).disabled((step==2&&(!terms||!privacy)) || (step==4&&app.profiles.profiles.isEmpty))}.padding(24).navigationTitle(step==0 ? "Sign In":"Setup").navigationBarTitleDisplayMode(.inline)}}
 @ViewBuilder var content:some View{switch step{case 0:Button("Continue on this device"){advance()}.buttonStyle(.borderedProminent);Text("Account sign-in is not configured in this build. Your profiles and plans stay on this device.").font(.footnote).foregroundStyle(.secondary)
 case 1:Button("Allow Location"){location.request();advance()}.buttonStyle(.borderedProminent);TextField("Or enter a city or address",text:$manualLocation).textFieldStyle(.roundedBorder);Button("Continue without location"){advance()}
 case 2:Toggle("I agree to the Terms of Service",isOn:$terms);Toggle("I agree to the Privacy Policy",isOn:$privacy);NavigationLink("Read Terms and Privacy"){LegalView()}
 case 3:VStack(alignment:.leading,spacing:12){Label("Your health information is optional.",systemImage:"heart.text.square").font(.headline);Text("The app only considers information you voluntarily provide. You can use it without adding medical conditions, medications, mental health information, or other health details. You can edit or remove this information later.");Text("The app does not access medical records or Apple Health.").foregroundStyle(.secondary)}
 default:VStack(alignment:.leading,spacing:12){Text("Who are you planning for?").font(.headline);Text("Profiles personalize environmental information for you or someone you care for.").foregroundStyle(.secondary);ForEach(app.profiles.profiles){p in Button{app.profiles.select(p.id)}label:{ProfileCard(profile:p,selected:p.id==app.profiles.selectedProfileID)}};Button("Create a profile",systemImage:"person.badge.plus"){creatingProfile=true};Button("Use demo profile Maya"){app.profiles.addSampleProfiles()}}.sheet(isPresented:$creatingProfile){ProfileEditorView(profile:.init(name:"",relationship:.myself),onSave:app.profiles.add,onDelete:nil)}}}
 var title:String{["Plan your day around the environment.","Use your location","Terms and privacy","You choose what to share","Choose a profile"][step]}
 var bodyText:String{["See how heat and air quality may affect your plans and explore lower-exposure options that fit your schedule.","We use your location to show conditions around you and compare conditions for your plans. You can also enter locations yourself.","Please review and agree before continuing.","Personal details are used only when they help personalize your experience.","Select an existing profile or create one to continue."][step]}
 var icon:String{["leaf","location","checkmark.shield","person.crop.circle.badge.checkmark","person.2"][step]}
 func advance(){if step<4{step+=1}else{app.finishOnboarding()}}
}
struct LegalView:View{var body:some View{List{Section("Terms of Service"){Text("Exposure Navigator provides planning information, not medical advice. Forecasts and modeled estimates can be incomplete or change. You make all decisions about your plans.")}Section("Privacy"){Text("Profiles, optional health details, and plans are stored on this device. Environmental services receive only coordinates and time needed for forecasts.")}}.navigationTitle("Terms & Privacy")}}
